export { default as TabTongQuan } from './TabTongQuan';
export { default as TabNguoiDung } from './TabNguoiDung';
export { default as TabXepHang } from './TabXepHang';
export { default as TabThanhToan } from './TabThanhToan';
export { default as TabTemplate } from './TabTemplate';
export { default as TabLichSu } from './TabLichSu';
export { default as TabCauHinh } from './TabCauHinh';
export { default as TabQuanTriGiaoDien } from './TabQuanTriGiaoDien';
export { default as TabChuyenDoiAdmin } from './TabChuyenDoi';
